name: "🐛 Bug Report"
description: File a structured report to help us reproduce and fix a bug.
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A clear, short description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: What steps leads to this behavior?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Production
        - Staging
        - Local Development
    validations:
      required: true