name: "DCO Compliance Check"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco:
    name: DCO Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: DCO Check Action
        uses: atylerq/dco-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
